struct BasicTypesModel {
    byte: u8,
    some_integer: i32,
    some_long: i64,
    some_unsigned_integer: u32,
    some_unsigned_long: u64,
    some_float_number: f32,
    some_double_number: f64,
    some_bool: bool,
    some_string: String,
    vector: Vec<String>,
    generic: LinearTable<f32, Test>,
    custom: MyModel,
    optional_string: Option<String>,
    optional_list_string: Option<Vec<String>>,
    list_optional_string: Vec<Option<String>>,
    list_list_string: Vec<Vec<String>>,
    optional_f32: Option<f32>,
}
